"""Hardcoded test DAG for MVP proof of the orchestrator pipeline."""
from __future__ import annotations

import asyncio
from collections.abc import Callable, Awaitable

from agent.orchestrator.contracts import ContractStore
from agent.orchestrator.dag import TaskDAG
from agent.orchestrator.models import TaskNode


def build_test_dag(project_path: str = ".") -> TaskDAG:
    """Build a hardcoded 7-task test DAG simulating a user-service scaffold.

    Wave 1 (parallel): init-project, init-contracts
    Wave 2: create-users-table (depends init-project), create-api-routes (depends init-contracts)
    Wave 3: create-user-model (depends create-users-table AND create-api-routes)
    Wave 4 (parallel): create-user-service, create-user-tests (both depend create-user-model)
    """
    dag = TaskDAG()

    # Wave 1
    dag.add_task(
        "init-project",
        label="Initialize project structure",
        contract_outputs=["db/schema.sql"],
    )
    dag.add_task(
        "init-contracts",
        label="Create initial contracts",
        contract_outputs=["api/openapi.yaml"],
    )

    # Wave 2
    dag.add_task(
        "create-users-table",
        label="Create users table SQL",
        contract_inputs=["db/schema.sql"],
        contract_outputs=["db/schema.sql"],
    )
    dag.add_dependency("init-project", "create-users-table")

    dag.add_task(
        "create-api-routes",
        label="Create user API routes",
        contract_inputs=["api/openapi.yaml"],
        contract_outputs=["api/openapi.yaml"],
    )
    dag.add_dependency("init-contracts", "create-api-routes")

    # Wave 3
    dag.add_task(
        "create-user-model",
        label="Create User Pydantic model",
        contract_inputs=["db/schema.sql", "api/openapi.yaml"],
    )
    dag.add_dependency("create-users-table", "create-user-model")
    dag.add_dependency("create-api-routes", "create-user-model")

    # Wave 4
    dag.add_task(
        "create-user-service",
        label="Create user service layer",
        contract_inputs=["db/schema.sql"],
    )
    dag.add_dependency("create-user-model", "create-user-service")

    dag.add_task(
        "create-user-tests",
        label="Create user test suite",
    )
    dag.add_dependency("create-user-model", "create-user-tests")

    assert dag.validate(), "Test DAG has cycles -- check dependencies"
    return dag


def build_test_task_executor(
    contract_store: ContractStore,
) -> Callable[[str, TaskNode], Awaitable[dict]]:
    """Return an async task executor that reads/writes contracts via ContractStore.

    For each task the executor:
    1. Reads every contract listed in task.contract_inputs
    2. Simulates work with a short sleep
    3. Writes meaningful dummy content to each contract in task.contract_outputs
    4. Returns a success dict
    """

    _DUMMY_CONTENT: dict[str, str] = {
        "db/schema.sql": (
            "CREATE TABLE users (\n"
            "  id TEXT PRIMARY KEY,\n"
            "  email TEXT UNIQUE NOT NULL,\n"
            "  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n"
            ");\n"
        ),
        "api/openapi.yaml": (
            "openapi: '3.0.0'\n"
            "info:\n"
            "  title: User API\n"
            "  version: '1.0'\n"
            "paths:\n"
            "  /users:\n"
            "    get:\n"
            "      summary: List users\n"
        ),
    }

    async def execute(task_id: str, task: TaskNode) -> dict:
        # Read contract inputs
        for name in task.contract_inputs:
            contract_store.read_contract(name)

        # Simulate work
        await asyncio.sleep(0.1)

        # Write contract outputs
        files_written: list[str] = []
        for name in task.contract_outputs:
            content = _DUMMY_CONTENT.get(name, f"# generated by {task_id}\n")
            contract_store.write_contract(name, content)
            files_written.append(name)

        return {"success": True, "files_written": files_written}

    return execute
