app = "shipyard-demo"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true

[mounts]
  source = "shipyard_data"
  destination = "/data"

[env]
  SHIPYARD_DB_PATH = "/data/shipyard.db"
