"""SessionStore Protocol — thin interface for swappable backends."""
from typing import Protocol, runtime_checkable
from store.models import Project, Run, Event, EditRecord, Conversation, GitOperation


@runtime_checkable
class SessionStore(Protocol):
    async def create_project(self, project: Project) -> Project: ...
    async def get_project(self, project_id: str) -> Project | None: ...
    async def list_projects(self) -> list[Project]: ...
    async def update_project(self, project: Project) -> Project: ...

    async def create_run(self, run: Run) -> Run: ...
    async def get_run(self, run_id: str) -> Run | None: ...
    async def update_run(self, run: Run) -> Run: ...
    async def list_runs(self, project_id: str) -> list[Run]: ...

    async def append_event(self, event: Event) -> None: ...
    async def replay_events(self, run_id: str, after_id: str | None = None) -> list[Event]: ...

    async def create_edit(self, edit: EditRecord) -> EditRecord: ...
    async def get_edits(self, run_id: str) -> list[EditRecord]: ...
    async def update_edit_status(self, edit_id: str, status: str) -> None: ...

    async def create_conversation(self, conv: Conversation) -> Conversation: ...
    async def get_conversations(self, project_id: str) -> list[Conversation]: ...

    async def log_git_op(self, op: GitOperation) -> None: ...
